version: 1
services:
  - type: web
    name: posua-2025
    env: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm preview
    autoDeploy: true
